ReaderDocument
NSString* ReaderDocument::guid
NSDate* ReaderDocument::fileDate
NSDate* ReaderDocument::lastOpen
NSNumber* ReaderDocument::fileSize
NSNumber* ReaderDocument::pageCount
Referenced by initWithFilePath:password:, updateProperties.
NSNumber* ReaderDocument::pageNumber
NSMutableIndexSet* ReaderDocument::bookmarks
NSString * ReaderDocument::fileName
Referenced by saveReaderDocument.
NSString* ReaderDocument::password
NSURL * ReaderDocument::fileURL
Referenced by initWithFilePath:password:, updateProperties.
ReaderDocument * ReaderDocument::withDocumentFilePath:password:(NSString *filename,[password] NSString *phrase)
References unarchiveFromFileName:password:.
ReaderDocument * ReaderDocument::unarchiveFromFileName:password:(NSString *filename,[password] NSString *phrase)
Referenced by withDocumentFilePath:password:.
id ReaderDocument::initWithFilePath:password:(NSString *fullFilePath,[password] NSString *phrase)
References _guid, _password, _bookmarks, _pageNumber, _fileName, fileURL, CGPDFDocumentCreateX, pageCount, _pageCount, _lastOpen, _fileDate, _fileSize, saveReaderDocument.
void ReaderDocument::saveReaderDocument()
References fileName.
Referenced by initWithFilePath:password:.
void ReaderDocument::updateProperties()
References fileURL, pageCount, _pageCount, _fileDate, _fileSize.
Referenced by ReaderViewController::initWithReaderDocument:.