CGPDFDocument.h
CGPDFDocumentRef CGPDFDocumentCreateX(CFURLRef theURL, NSString *password)
Referenced by ReaderContentPage::initWithURL:page:password:, ReaderDocument::initWithFilePath:password:, ReaderDocumentOutline::outlineFromFileURL:password:.
BOOL CGPDFDocumentNeedsPassword(CFURLRef theURL, NSString *password)