ReaderThumbCache
ReaderThumbCache * ReaderThumbCache::sharedInstance()
Referenced by ReaderContentView::showPageThumb:page:password:guid:.
void ReaderThumbCache::touchThumbCacheWithGUID:(NSString *guid)
References thumbCachePathForGUID:.
Referenced by ReaderViewController::initWithReaderDocument:.
void ReaderThumbCache::createThumbCacheWithGUID:(NSString *guid)
References thumbCachePathForGUID:.
void ReaderThumbCache::removeThumbCacheWithGUID:(NSString *guid)
References thumbCachePathForGUID:.
void ReaderThumbCache::purgeThumbCachesOlderThan:(NSTimeInterval age)
NSString * ReaderThumbCache::thumbCachePathForGUID:(NSString *guid)
Referenced by createThumbCacheWithGUID:, removeThumbCacheWithGUID:, touchThumbCacheWithGUID:.
id ReaderThumbCache::thumbRequest:priority:(ReaderThumbRequest *request,[priority] BOOL priority)
References ReaderThumbRequest::thumbView, ReaderThumbView::operation, ReaderThumbQueue::sharedInstance, ReaderThumbQueue::addLoadOperation:.
Referenced by ReaderContentView::showPageThumb:page:password:guid:.
void ReaderThumbCache::setObject:forKey:(UIImage *image,[forKey] NSString *key)
void ReaderThumbCache::removeObjectForKey:(NSString *key)
void ReaderThumbCache::removeNullForKey:(NSString *key)
void ReaderThumbCache::removeAllObjects()